package at.campus.backend.modules.courses.model;

import java.util.UUID;

/**
 * DTO exposed via REST API.
 *
 * Responsibilities:
 * - Represents Course data in HTTP requests/responses
 * - Converts between API representation and domain model
 *
 * IMPORTANT:
 * - DTO contains NO business logic
 * - DTO does NOT access database
 */
public record CourseDto(
        UUID courseId,
        String title,
        String description,
        int ects,
        String abbreviation,
        String language,
        java.math.BigDecimal sws,
        Integer semester,
        String kind,
        String detailsHtml,
        Object content,
        Object learningOutcomes,
        Object teachingMethod,
        Object examMethod,
        Object literature,
        Object teachingLanguage,
        String sourceUrl
) {

    // -------------------------
    // DOMAIN -> DTO
    // -------------------------
    public static CourseDto fromDomain(Course course) {
        return new CourseDto(
                course.getCourseId(),
                course.getTitle(),
                course.getDescription(),
                course.getEcts(),
                course.getAbbreviation(),
                course.getLanguage(),
                course.getSws(),
                course.getSemester(),
                course.getKind(),
                course.getDetailsHtml(),
                course.getContent(),
                course.getLearningOutcomes(),
                course.getTeachingMethod(),
                course.getExamMethod(),
                course.getLiterature(),
                course.getTeachingLanguage(),
                course.getSourceUrl()
        );
    }

    // -------------------------
    // DTO -> DOMAIN (CREATE)
    // -------------------------
    // Used for POST /api/courses
    // ID is generated by backend / DB
    public Course toDomain() {
        return new Course(
                null,
                title,
                description,
                ects,
                abbreviation,
                language,
                sws,
                semester,
                kind,
                detailsHtml,
                content,
                learningOutcomes,
                teachingMethod,
                examMethod,
                literature,
                teachingLanguage,
                sourceUrl
        );
    }

    // -------------------------
    // DTO -> DOMAIN (UPDATE)
    // -------------------------
    // Used for PUT /api/courses/{id}
    // Path variable ID is the source of truth
    public Course toDomain(UUID courseId) {
        return new Course(
                courseId,
                title,
                description,
                ects,
                abbreviation,
                language,
                sws,
                semester,
                kind,
                detailsHtml,
                content,
                learningOutcomes,
                teachingMethod,
                examMethod,
                literature,
                teachingLanguage,
                sourceUrl
        );
    }
}
